// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/images/KrankyBearMediaPlayer.png
var resourceKrankyBearMediaPlayerPngData []byte
var resourceKrankyBearMediaPlayerPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearMediaPlayer.png",
	StaticContent: resourceKrankyBearMediaPlayerPngData,
}

//go:embed assets/images/KrankyBearHardHat.png
var resourceKrankyBearHardHatPngData []byte
var resourceKrankyBearHardHatPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearHardHat.png",
	StaticContent: resourceKrankyBearHardHatPngData,
}

